serverAddr = "course.prafdin.ru"
serverPort = 7000

auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "app-chesnokov"
type = "http"
localPort = 8181
customDomains = ["app.chesnokov.course.prafdin.ru"]

[[proxies]]
name = "ssh-chesnokov"
type = "tcp"
localPort = 22
remotePort = 3129

